# Generated by Django 5.2.3 on 2025-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(default=323265, max_length=200),
            preserve_default=False,
        ),
    ]
