# Generated by Django 5.2.3 on 2025-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_available',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Occupied')], default=1),
        ),
    ]
