# Generated by Django 5.2.3 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unit_is_available_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_of_payment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'GCash'), (3, 'Bank Transfer'), (4, 'Check'), (5, 'Credit Card')], default=1),
        ),
    ]
