# Generated by Django 5.2.3 on 2025-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
